#!/usr/bin/python
#
# run all tests
#

import os
import sys
import signal
import time
import subprocess

os.system("make clean;unset CILK;unset CILKP;make;")

def signal_handler(signal,frame):
  print "bye\n"
  sys.exit(0)
signal.signal(signal.SIGINT,signal_handler)

def shellGetOutput(str) :
  process = subprocess.Popen(str,shell=True,stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
  output, err = process.communicate()
  
  if (len(err) > 0):
      raise NameError(str+"\n"+output+err)
  return output

#testfiles = []
testfiles = ["10Midentical","10Mrandom","10Msqrtn","chr22.dna","etext99","howto.txt","jdk13c","rctail96","rfc","sprot34.dat","thesaurus.doc","w3c2","wikisamp.xml","wikisamp9.xml"]
#testfiles = ["wikisamp9.xml"]


apps = ["lz77_1","lz77_2","lz77_3"]

for app in apps:
  for testfile in testfiles :
    ss = "./"+app+" -i testData/"+testfile
    print app + " " + testfile 
    print shellGetOutput(ss)
    sys.stdout.flush()
